name: Build docker image
on:
  push:
    branches-ignore: [main]
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        uses: docker/build-push-action@v2
  lint_source:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Check formatting
        run: |
          black --check ./dude

      - name: Check styleguide
        run: |
          flake8 --max-line-length=100 ./dude

      - name: Lint
        run: |
          pylint ./dude
